"""add_exam_schedule_table

Revision ID: c0247d7f509f
Revises: 20260901_01_answer_source
Create Date: 2026-09-03 16:40:48.927712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c0247d7f509f'
down_revision = '20260901_01_answer_source'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create the new exam_schedules table, skip SQLite-incompatible constraint changes
    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_period', sa.String(length=50), nullable=False, comment='考期，如2026年10月'),
    sa.Column('register_start', sa.Date(), nullable=True, comment='报名开始日期'),
    sa.Column('register_end', sa.Date(), nullable=True, comment='报名结束日期'),
    sa.Column('exam_start', sa.Date(), nullable=False, comment='考试开始日期'),
    sa.Column('exam_end', sa.Date(), nullable=True, comment='考试结束日期（多日考试）'),
    sa.Column('result_date', sa.Date(), nullable=True, comment='成绩发布日期'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注，如考试时间段、注意事项等'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='数据来源URL'),
    sa.Column('crawled_at', sa.DateTime(), nullable=False, comment='爬取时间'),
    sa.Column('is_past', sa.Integer(), nullable=True, comment='0未过期 1已过期'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_schedules_exam_period'), 'exam_schedules', ['exam_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_schedules_exam_period'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    # ### end Alembic commands ###
